_wandb:
    value:
        cli_version: 0.21.0
        e:
            cui1z9i3lr6yjbmqs4iuzv2hw54kdxna:
                codePath: src\bertv2.py
                codePathLocal: bertv2.py
                cpu_count: 16
                cpu_count_logical: 22
                disk:
                    /:
                        total: "1022020096000"
                        used: "957429714944"
                email: johnnyteoh8888@gmail.com
                executable: C:\Users\peter\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe
                git:
                    commit: 1b7b058de2e4458a224b9d83a4783c390399fb73
                    remote: https://github.com/johnnyteoh90/MSc-Research-Project.git
                host: Johnnygains
                memory:
                    total: "33685757952"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\peter\Desktop\MSc-Research-Project\src\bertv2.py
                python: CPython 3.10.11
                root: C:\Users\peter\Desktop\MSc-Research-Project\src
                startedAt: "2025-07-21T11:23:51.563121Z"
                writerId: cui1z9i3lr6yjbmqs4iuzv2hw54kdxna
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
            "3":
                - 7
                - 66
            "4": 3.10.11
            "5": 0.21.0
            "6": 4.31.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
auto_find_batch_size:
    value: false
bf16:
    value: false
bf16_full_eval:
    value: false
data_seed:
    value: None
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_pin_memory:
    value: true
ddp_backend:
    value: None
ddp_broadcast_buffers:
    value: None
ddp_bucket_cap_mb:
    value: None
ddp_find_unused_parameters:
    value: None
ddp_timeout:
    value: 1800
debug:
    value: '[]'
deepspeed:
    value: None
disable_tqdm:
    value: false
do_eval:
    value: true
do_predict:
    value: false
do_train:
    value: false
eval_accumulation_steps:
    value: None
eval_batch_size:
    value: 8
eval_delay:
    value: 0
eval_steps:
    value: None
evaluation_strategy:
    value: epoch
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: '[]'
fsdp_config:
    value: '{''fsdp_min_num_params'': 0, ''xla'': False, ''xla_fsdp_grad_ckpt'': False}'
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: None
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
greater_is_better:
    value: true
group_by_length:
    value: false
half_precision_backend:
    value: auto
hub_model_id:
    value: None
hub_private_repo:
    value: false
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
ignore_data_skip:
    value: false
include_inputs_for_metrics:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: None
label_smoothing_factor:
    value: 0
learning_rate:
    value: 2e-05
length_column_name:
    value: length
load_best_model_at_end:
    value: true
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: logs
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 50
logging_strategy:
    value: steps
lr_scheduler_type:
    value: linear
max_grad_norm:
    value: 1
max_steps:
    value: -1
metric_for_best_model:
    value: f1
mp_parameters:
    value: ""
no_cuda:
    value: false
num_train_epochs:
    value: 4
optim:
    value: adamw_hf
optim_args:
    value: None
output_dir:
    value: outputs/bert_meta
overwrite_output_dir:
    value: false
past_index:
    value: -1
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 8
per_gpu_eval_batch_size:
    value: None
per_gpu_train_batch_size:
    value: None
prediction_loss_only:
    value: false
push_to_hub:
    value: false
push_to_hub_model_id:
    value: None
push_to_hub_organization:
    value: None
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_unused_columns:
    value: true
report_to:
    value: '[''tensorboard'', ''wandb'']'
resume_from_checkpoint:
    value: None
run_name:
    value: outputs/bert_meta
save_on_each_node:
    value: false
save_safetensors:
    value: false
save_steps:
    value: 500
save_strategy:
    value: epoch
save_total_limit:
    value: None
seed:
    value: 42
sharded_ddp:
    value: '[]'
skip_memory_metrics:
    value: true
tf32:
    value: None
torch_compile:
    value: false
torch_compile_backend:
    value: None
torch_compile_mode:
    value: None
torchdynamo:
    value: None
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: None
train_batch_size:
    value: 8
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_mps_device:
    value: false
warmup_ratio:
    value: 0
warmup_steps:
    value: 0
weight_decay:
    value: 0
xpu_backend:
    value: None
